apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: certificates
  namespace: ${NAMESPACE@microservice-config}
  labels:
    service: certificate
spec:
  storageClassName: standard
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-0572afea6012336e3"
