apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microservice-ingress
  namespace: ${NAMESPACE@microservice-config}
spec:
  rules:
  - host: ${HOST@microservice-config}
    http:
      paths:
      - path: /${PATH_URL_APP@microservice-auth-config}/backend
        backend:
          serviceName: microservice-auth-graph-service
          servicePort: ${PORT_GRAPH@microservice-auth-config}
      - path: /${PATH_URL_APP@microservice-auth-config}/backend
        backend:
          serviceName: microservice-auth-graph-service
          servicePort: ${PORT_GRAPH@microservice-auth-config}
      - path: /${PATH_URL_APP@microservice-auth-config}
        backend:
          serviceName: microservice-auth-web-service
          servicePort: ${PORT_APP@microservice-auth-config}
