apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  namespace: ${NAMESPACE@microservice-config}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
